# Generated by Django 3.2.7 on 2021-09-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.subdivision', verbose_name='Parent Item')),
            ],
            options={
                'verbose_name': 'Subdivision item',
                'verbose_name_plural': 'Subdivision items',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Full name')),
                ('position', models.CharField(max_length=250)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hiring', models.DateField(verbose_name='Hiring date')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.subdivision', verbose_name='Subdivision')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
